typography_spectrum: 0.34084
color:
  brandColors:
    - '#000000'
    - '#135a74'
    - '#1e94bf'
    - '#8fe8ff'
    - '#818481'
  brandStrength: 0.33101697731763124
  lightness: 0.6772271364461631
  saturation: 0.8525167109910399
  rhythmicContrast: 0.07745640375651419
opengraph: {}
layout_spectrum: 0.15648
analytics: {}
name: Heavenstar
cta: {}
navigation:
  - name: Heavenstar's facebook page.
    url: 'https://www.facebook.com/heavenstar777/'
    type: external
title: HEAVENSTAR QUALITY LEATHER & GRAPHIC DESIGN
description: '"Crafting in the USA"'
purpose: []
