name: Heavenstar
favicon: null
layout_spectrum: 0.92515
typography_spectrum: 0.34084
title: 'HEAVENSTAR QUALITY LEATHER & GRAPHIC DESIGN'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#135a74'
    - '#1e94bf'
    - '#8fe8ff'
    - '#818481'
  brandStrength: 0.33101697731763124
  lightness: 0.6772271364461631
  saturation: 0.8525167109910399
  rhythmicContrast: 0.07745640375651419
purpose: []
